<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLDqFxsp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLDqFxsp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLDqFxsp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLDqFxsp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLDqFxsp\App_KernelDevDebugContainer([
    'container.build_hash' => 'LDqFxsp',
    'container.build_id' => '5e7c29dd',
    'container.build_time' => 1608732167,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLDqFxsp');
