<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2faZ5aw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2faZ5aw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2faZ5aw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2faZ5aw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2faZ5aw\App_KernelDevDebugContainer([
    'container.build_hash' => '2faZ5aw',
    'container.build_id' => 'cf0cc095',
    'container.build_time' => 1606070944,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2faZ5aw');
