<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUamt3Zt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUamt3Zt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUamt3Zt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUamt3Zt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUamt3Zt\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uamt3Zt',
    'container.build_id' => '3d761d78',
    'container.build_time' => 1606069493,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUamt3Zt');
